package es.reji.views.avisolegal;

import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.PageTitle;
import es.reji.views.MainLayout;

@PageTitle("Aviso legal")
@Route(value = "avisolegal", layout = MainLayout.class)
public class AvisolegalView extends VerticalLayout {

    public AvisolegalView() {
        setSpacing(false);

        add(new H1("Aviso Legal"));
        add(new H2("1.- TITULARIDAD DEL PORTAL"));
        add(new Paragraph("REJI S.A. con domicilio en C/ Avenida de la Universidad, SN CP 11519 Puerto Real, Cádiz y con NIF A05050505, inscrita en el Registro Mercantil de Cádiz, Tomo 8081, Libro 0, Folio 69, Seccion 8 Hoja M-130462 Inscripción 1ª es la titular de la página web http://www.cinesreji.com (en lo sucesivo, el Portal) y permite su acceso a los usuarios de Internet."));
        add(new H2("2.- CONDICIONES GENERALES DE UTILIZACIÓN Y ACEPTACIÓN DE LAS MISMAS"));
        add(new Paragraph("La navegación y la utilización de los servicios del portal suponen la aceptación como Usuario y sin reservas de ningún tipo, de todas las condiciones generales de utilización y cualesquiera otras que puedan existir en relación con la prestación de servicios de REJI S.A. podrá en todo momento y sin previo aviso, modificar las presentes condiciones generales a fin de que sean conocidas con carácter previo por los usuarios. Cualquier cambio que se produzca en éstas será comunicado en la página principal del portal durante un plazo que se entienda razonable."));
        add(new H2("3.- POLÍTICA DE PROTECCIÓN DE DATOS DE CARÁCTER PERSONAL"));
        add(new H3("3.1.- Política de Protección de Datos de Carácter Personal"));
        add(new Paragraph("El titular de la web y responsable del tratamiento, es REJI S.A. cuyos constan ya anteriormente, titular del portal permite su acceso a los usuarios de Internet que estén conforme con esta política de uso de la misma, con el fin tanto de proporcionar información sobre los servicios que presta esta sociedad así como en el caso de admitirse, previa y expresamente por escrito por parte de la referida sociedad, acordar la prestación de servicios a través del Portal."));
        add(new Paragraph("Contacto por E-Mail: lopd@cinesreji.es"));
        add(new Paragraph("La sociedad responsable tiene como Delegado de Protección de Datos a D. Esperanza Cano Canalejas"));
        add(new Paragraph("Para cualquier gestión o solicitud con respecto a la privacidad de REJI S.A., el usuario podrá dirigirse al correo electrónico : lopd@cinesreji.es"));
        add(new H3("3.2.- Finalidad ¿Con qué finalidades tratamos sus datos?"));
        add(new Paragraph("La navegación y la utilización de los servicios del portal suponen la aceptación como Usuario y sin reservas de ningún tipo, de todas las condiciones generales de utilización y cualesquiera otras que puedan existir en relación con la prestación de servicios de REJI S.A. podrá en todo momento y sin previo aviso, modificar las presentes condiciones generales a fin de que sean conocidas con carácter previo por los usuarios. Cualquier cambio que se produzca en éstas será comunicado en la página principal del portal durante un plazo que se entienda razonable."));
        add(new Paragraph("La presente política de privacidad es de aplicación a REJI S.A. sólo tratará los datos personales de los usuarios que libremente y de forma voluntaria se los proporcione a través de los formularios de contacto insertados en la Web o en su caso, remitidos o enviados presencialmente en oficinas o dependencias de esta sociedad, o en su caso, mediante correo electrónico, sms o cualquier otro medio que la tecnología permita"));
        add(new Paragraph("La base jurídica que nos habilita para el tratamiento de sus datos personales es el propio consentimiento del interesado. El hecho de cumplimentar el mencionado formulario implica que el Usuario acepta y autoriza el registro y tratamiento de sus datos personales en los ficheros titularidad de REJI S.A. con la finalidades que a continuación se detallan, y reconoce que la información y los datos personales que indica son suyos, exactos y ciertos, y corresponden a una persona mayor de 16 años."));
        add(new Paragraph("En relación a la información que nos hace llegar, REJI S.A. informa al Usuario de la existencia de un tratamiento de datos de carácter personal creado con los datos obtenidos en la página web o por cualquier otro medio al margen de internet por, para y bajo la responsabilidad de REJI S.A."));
        add(new Paragraph("Dicho fichero ha sido creado con la finalidad de: (1) Posibilitar la adquisición de productos y/o servicios ofertados por REJI S.A., inclusive mediante la remisión del enlace para la descarga y, en su caso, impresión de las entradas de cine, así como consultas sobre dichas adquisiciones (2) Facilitar información sobre la prestación de los servicios y/o productos ofrecidos por la sociedad, a través del portal, o bien al margen de internet, así como atender y gestionar las consultas y/o peticiones realizadas por los usuarios por cualquier vía, inclusive la finalidad de enviarles comunicaciones comerciales sobre sus productos, actividades, noticias, ofertas y promociones. (3) REJI S.A. igualmente remitirá comunicaciones comerciales de productos de otras empresas con las que haya suscrito acuerdos de cuyos descuentos, beneficios o adquisición/ utilización pueda beneficiarse la persona que informó de sus datos y que ha autorizado para la remisión de publicidad a la dirección electrónica, teléfono o postal informada. En ningún caso ello se hará mediante cesión de datos. (4) Garantizar el funcionamiento de la web y aplicaciones en las que participe o sean titularidad de REJI S.A., así como realizar estudios estadísticos sobre el uso de la web (5) Gestionar su participación en sorteos u otras actividades con premios promovido por nosotros y / o nuestros socios comerciales."));
        add(new Paragraph("REJI S.A. informa que, cuando el Usuario realice la compra de entradas de cine o a eventos realizados por REJI S.A. y/u otros bienes o servicios ofrecidos por REJI S.A. a través del Web, desde que muestre su voluntad de adquirir una entrada los datos que facilite durante el proceso de compra serán informados y recabados directamente por REJI SOCIEDAD ANONIMA para generar la entrada, atendiendo a las obligaciones del Instituto de la Cinematografía y de las Artes Audiovisuales (ICAA) organismo autónomo adscrito a la Secretaría de Estado de Cultura, así como por la pasarela de pago que use la referida compañía"));
        add(new Paragraph("Los plazos de conservación de los datos que los usuarios nos proporcionen se limitarán a lo estrictamente necesario en cuanto no desemboque en una relación negocial duradera o no exista un interés legítimo en su conservación por cambiar los criterios organizativos o necesidades de la empresa. La información suministrada se destruirán en el plazo máximo de dos años desde que se recaben."));
        add(new H3("3.3.- Legitimación ¿Cuál es la legitimación para el tratamiento de sus datos?"));
        add(new Paragraph("La base legal para el tratamiento de los datos personales de los usuarios es el propio consentimiento del interesado. Asimismo la oferta de servicios está basada en el consentimiento que se solicita al usuario sin que ningún caso la retirada de este consentimiento condicione la ejecución de otras finalidades. El usuario no tiene la obligación de facilitarnos sus datos personales, pero en caso de no facilitarnos los datos mínimos solicitados, y en su caso, los elementos para su verificación, no se podrá dar curso a las comunicaciones y solicitudes que se realicen mediante el portal, tales como atender las consultas, enviar información de interés, así como, cuando proceda, contactar, dejar un comentario, participar en el Blog etc. La información que tenga el carácter de necesario para poder hacer uso de los servicios ofertados por REJI S.A. en internet se marcarán con un asterisco (*) Además informamos que el usuario podrá revocar el consentimiento para la recogida y tratamiento de sus datos personales en cualquier momento, mediante el procedimiento que establecemos para ello, sin que ello afecte a la licitud del tratamiento basado en el consentimiento previo a su retirada. En la medida que no se comunique por escrito lo contrario, se entenderá que los datos informados se encuentran actualizados, siendo responsabilidad del informante aportar datos actuales y veraces."));
        add(new H3("3.4.- Destinatarios ¿A qué destinatarios se comunicarán sus datos?"));
        add(new Paragraph("Los datos que se recogen en esta web mediante los formularios correspondientes así como en la relación negocial directa que se entable serán objeto de comunicación a otras empresas que ejercen de encargados del tratamiento de datos personales, y que solo tratarán los datos conforme a las estrictas indicaciones que REJI S.A. establece con dichos encargados. En todo caso los datos serán comunicados dentro del espacio de la Unión Europea, solo para los fines anteriormente indicados y nunca facultarán a la utilización de estos datos al margen del fin concreto que les haya solicitado REJI S.A., es decir, nunca supondrán una molestia para el titular de los datos. El titular de los datos podrá solicitar verbal o por escrito que sus comunicaciones y temas que son objeto de una relación negocial con este despacho se remitan a diversos destinatarios o personas de su confianza. Es necesario que cuando cambie dicha circunstancia el titular de los datos lo haga constar por escrito y expresamente a esta sociedad para evitar cualquier tipo de perjuicio para el mismo."));
        add(new H3("3.5.- Derechos ¿Cuáles son sus derechos cuando nos facilita sus datos?"));
        add(new Paragraph("A los usuarios de la web titularidad de REJI S.A. se les garantiza los derechos que se establecen en la legislación en materia de Protección de Datos Personales: Los usuarios tienen derecho a oponerse al tratamiento de sus datos personales, por lo que REJI S.A. dejará de tratar sus datos, salvo si existen motivos legítimos, imperiosos, o el ejercicio o la defensa de posibles reclamaciones."));
        add(new Paragraph("Los usuarios tienen la facultad de solicitar a REJI S.A. que limite los tratamientos de sus datos personales cuando se cumplan los requisitos que el Reglamento UE 2016/679 exige. Por último informamos que cualquier interesado podrá presentar una reclamación ante la Agencia Española de Protección de Datos, especialmente cuando no haya obtenido satisfacción en el ejercicio de sus derechos."));
        add(new Paragraph("El usuario tiene derecho a obtener una confirmación sobre si en REJI S.A. se están tratando datos personales que le conciernan o no, así como acceder a sus datos personales y solicitar la rectificación de los datos que sean inexactos o, en su caso, solicitar su supresión cuando, entre otros motivos, los datos ya no sean necesarios para los fines que fueron recogidos. En cualquier momento podrá ejercitar los derechos de acceso, rectificación, supresión, limitación, oposición y portabilidad de los datos, así como reclamación ante la autoridad competente de control. La cancelación de sus datos, deberá solicitarlo expresamente si ello fuese de su interés directamente a REJI S.A. en los datos de contacto antes informados o a la dirección de correo electrónico lopd@cinesreji.es."));
        add(new H3("3.6.-Duración."));
        add(new Paragraph("Los datos se conservarán mientras se mantenga la finalidad para la que han sido recabados que en este caso, en que el los datos se interesan de los usuarios principalmente para ofrecerle nuestros servicios y productos se mantendrán mientras no se digan lo contrario, sin perjuicio de que la sociedad cada cierto tiempo haga algún tipo de gestión a fin de confirmar el interés de los usuarios o titulares de los datos de que mantengamos los mismos."));
        add(new H2("4. POLÍTICA DE COOKIES Y GEOLOCALIZACIÓN"));
        add(new Paragraph("4.1.- Durante su visita a nuestro website, REJI S.A. puede utilizar cookies. Una cookie no es más que un fichero de texto que algunos servidores piden a nuestro navegador que escriba en nuestro disco duro, con información acerca de lo que hemos estado haciendo por sus páginas. De este modo, se puede controlar, por ejemplo, si usted está autentificado en una determinada web o ya ha visitado una determinada página, con el objeto de ofrecerle un mejor servicio. Las cookies que se utilizan en los sitios y páginas web del Portal se asocian únicamente con el navegador de un ordenador determinado (un Usuario anónimo), y no proporcionan por sí el nombre y apellidos del Usuario. Gracias a las cookies, resulta posible que el sitio web reconozca los navegadores de los Usuarios registrados después de que éstos se hayan registrado por primera vez, sin que se tengan que registrarse en cada visita para acceder a las áreas y servicios reservados exclusivamente a ellos. El Usuario tiene la posibilidad de configurar su navegador para ser avisado en pantalla de la recepción de cookies y para impedir la instalación de cookies en su disco duro. Para eliminarlas, vaya usted a Herramientas, luego a Opciones de Internet, y en la pestaña de General, bajo el apartado de Archivos Temporales de Internet pulse sobre Eliminar cookies."));
        add(new Paragraph("4.2.-Igualmente, informamos al Usuario que determinadas funcionalidades de la Web utilizan la navegación considerando la ubicación para poder proporcionarle la información más relevante en cada caso, así como para ofrecerle ciertos servicios. Aunque la navegación considerando la ubicación es siempre una elección del Usuario, en los casos en los que el Usuario la rechace la Web no podrá ofrecerle las funcionalidades o proporcionarle los contenidos basados en dicha ubicación."));
        add(new Paragraph("Se hace saber que cuando el Usuario facilite sus datos personales para beneficiarse de los servicios o productos de un tercero anunciante y así se informe al Usuario, REJI S.A. no los utilizará para remitirle promociones u ofertas sobre sus propios servicios o productos. De esta manera, sus datos quedarán incorporados en un fichero titularidad de dicho anunciante, y serán tratados para las finalidades que en cada formulario se recojan. En estos supuestos, el Usuario deberá dirigirse al anunciante en cuestión, mediante el procedimiento y a la dirección indicada en cada formulario, para ejercer sus derechos de acceso, rectificación, cancelación y oposición. Asimismo, cuando a través de la Web el Usuario realice algún comentario en redes sociales, en cuanto a los datos que facilite a través de las mismas, el responsable de su tratamiento será la red social y no REJI S.A., debiéndose dirigir a la misma para ejercer sus derechos de acceso, rectificación, cancelación y oposición."));
        add(new H2("5.- PROPIEDAD INDUSTRIAL E INTELECTUAL. POLÍTICA DE HIPERENLACES"));
        add(new Paragraph("5.1.- Todos los contenidos incluidos en el Portal y en particular las marcas, nombres comerciales, signos distintivos, diseños industriales, textos, fotografías, gráficos, logotipos, iconos, software o cualesquiera otros signos susceptibles de utilización industrial y comercial están protegidos por derechos de propiedad industrial e intelectual titularidad de REJI S.A., o bien son de terceros titulares de los mismos que han autorizado su inclusión en el Portal. Queda por lo tanto prohibida cualquier utilización, y/o reproducción de los mismos, total o parcial, sin consentimiento expreso de REJI S.A."));
        add(new Paragraph("5.2.- REJI S.A. no será responsable de la infracción de los derechos de propiedad intelectual o industrial de terceros que pudieran derivarse de la inclusión en el Portal de marcas, nombres comerciales, diseños industriales, diseños, textos, fotografías, gráficos, logotipos, iconos o software pertenecientes a terceros que hayan declarado ser titulares de los mismos al incluirlos en el Portal."));
        add(new Paragraph("5.3.- En ningún caso se entenderá que el acceso y la navegación del Usuario implica una autorización o que se efectúa renuncia, transmisión, cesión total o parcial de dichos derechos ni la concesión de ningún derecho ni expectativa de derecho y en concreto, de la alteración, transformación, explotación, reproducción, distribución o comunicación pública sobre dichos contenidos sin la previa autorización expresa de REJI S.A. o de los titulares correspondientes. No se podrá establecer ningún vínculo al Portal desde cualquier otra web sin el consentimiento previo y expreso de REJI S.A."));
        add(new Paragraph("5.4.- REJI S.A. no será responsable del contenido de las páginas web de destino que se establezcan mediante vínculos en el Portal, así como tampoco de las infracciones de derechos de terceros en las que dichas páginas pudieran incurrir."));
        add(new Paragraph("5.5.- REJI S.A. se reserva el derecho a realizar cambios en su portal, sin previo aviso, al objeto de mantener actualizada su información, añadiendo, modificando, corrigiendo o eliminando los contenidos publicados o el diseño de la web."));
        add(new H2("6.- RESPONSABILIDAD DE REJI S.A."));
        add(new Paragraph("El Usuario reconoce y acepta que la utilización del Portal y de sus servicios de las que sea titular o en las que participe REJI S.A. lo realiza bajo su entera responsabilidad. REJI S.A. únicamente responderá de los daños que el Usuario pueda sufrir como consecuencia de la utilización del portal cuando dichos daños sean imputables a una actuación dolosa de REJI S.A. No obstante, REJI S.A. declara haber adoptado todas las medidas necesarias, dentro de sus posibilidades y del estado de la tecnología, para garantizar el funcionamiento del Portal y evitar la existencia y transmisión de virus y otros componentes que puedan perjudicar al Usuario."));
        add(new H2("7.-OBLIGACIONES DEL USUARIO"));
        add(new Paragraph("El Usuario se obliga a usar los contenidos del portal de forma diligente, correcta y lícita y se compromete a abstenerse de: "));
        add(new Paragraph("Utilizar los contenidos con fines o efectos contrarios a la ley, a la moral y a las buenas costumbres o al orden público."));
        add(new Paragraph("Reproducir, copiar, distribuir, permitir el acceso del público a través de cualquier modalidad de comunicación pública, transformar o modificar los contenidos."));
        add(new Paragraph("Utilizar los contenidos del portal para remitir publicidad, comunicaciones con fines de venta directa o con cualquier otra clase de finalidad comercial, mensajes no solicitados dirigidos a una pluralidad de personas con independencia de su finalidad, así como a abstenerse de comercializar o divulgar de cualquier modo dicha información."));
        add(new H2("8.- RELACIÓN ENTRE USUARIO Y REJI S.A."));
        add(new Paragraph("8.1.- REJI S.A. no tiene obligación de leer, analizar y responder a los emails, peticiones y/o consultas que se realicen a través del Portal o cualquier otro canal de comunicación. Por excepción de lo anterior, si será objeto de análisis cuantas peticiones se realicen sobre protección de datos, debiendo hacerse constar en el asunto del email expresamente la expresión “protección de datos” para que se pueda realizar el oportuno filtrado y atender en oportuna forma la solicitud concreta que se interesará y desarrollará en el del mail o del cuestionario."));
        add(new Paragraph("8.2.- Con la finalidad de evitar engaños o perjuicios, se ruega que en caso de solicitarse desde una dirección de email de esta sociedad o mediante la web de REJI S.A. información sensible o que no guarde relación con los contactos que se están manteniendo, se abstenga de realizar la actividad interesada y lo ponga directamente en conocimiento de esta sociedad si puede ser mediante un correo electrónico a lopd@cinesreji.es."));
        add(new H2("9.-COMUNICACIONES COMERCIALES"));
        add(new Paragraph("REJI S.A. podrá enviar comunicaciones comerciales por cualquier medio con pleno respeto a la legislación que en materia de protección de datos personales se encuentre vigente. Para las comunicaciones comerciales realizadas a través del correo electrónico y medios equivalentes en cumplimiento de lo dispuesto en la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico, será debidamente recabado el consentimiento del Usuario en el momento de recoger los datos correspondientes. El Usuario podrá revocar en cualquier momento el consentimiento prestado a la recepción de las comunicaciones personales con la simple notificación de su voluntad a REJI S.A."));
        add(new H2("10.- LEGISLACIÓN APLICABLE"));
        add(new Paragraph("Las relaciones establecidas entre el Usuario y el titular del Portal y aplicaciones se regirán por lo dispuesto en la normativa vigente acerca de la legislación aplicable y la jurisdicción competente. No obstante, para los casos en que no existiendo previsión contractual, y la normativa prevea la posibilidad a las partes de someterse a un fuero, el Usuario, con renuncia expresa a cualquier otro fuero que pudiera corresponderles, se someten a los Juzgados y Tribunales del término municipal Sevilla. En todo caso serán aplicables las normas del Ordenamiento Jurídico Español."));
        add(new Paragraph("Esta es la información legal de la propietaria de la web."));
        add(new Paragraph("Para consultas y ayuda utilice el link de la parte inferior izquierda o envie un mail a admin@cinesreji.com"));
        
        setSizeFull(); 
        getStyle().set("text-align", "justify");
    }
}
